WITH RECURSIVE HOURS AS (
    SELECT 0 AS HR
    
    UNION ALL
    
    SELECT HR + 1
    FROM HOURS
    WHERE HR < 23
)

SELECT H.HR AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
ON H.HR = HOUR(A.DATETIME)
GROUP BY H.HR
ORDER BY H.HR;