WITH RENTAL AS (
    SELECT CAR_ID,
           MONTH(START_DATE) AS MONTH,
           COUNT(*) OVER (PARTITION BY CAR_ID) AS TOTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
      AND START_DATE < '2022-11-01'
)

SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM RENTAL
WHERE TOTAL >= 5
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;